### ISSUE TITLE
Cannot read property 'clone' of undefined

### ISSUE THREAD

**Issue by tkisme** [google/material-design-lite#1447]
```
gulp demos
[11:43:07] Using gulpfile ~/MEGAsync/cloud/gitbucket/material-design-lite/gulpfile.js
[11:43:07] Starting 'demoresources'...
[11:43:07] Finished 'demoresources' after 389 ms
[11:43:07] Starting 'demos'...
/Users/tk/MEGAsync/cloud/gitbucket/material-design-lite/node_modules/gulp-header/index.js:58
    var file = _file.clone({ contents: false });
                    ^
TypeError: Cannot read property 'clone' of undefined
    at DestroyableTransform.EndStream [as _flush] (/Users/tk/MEGAsync/cloud/gitbucket/material-design-lite/node_modules/gulp-header/index.js:58:21)
    at DestroyableTransform.<anonymous> (/Users/tk/MEGAsync/cloud/gitbucket/material-design-lite/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:104:17)
    at prefinish (/Users/tk/MEGAsync/cloud/gitbucket/material-design-lite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:492:12)
    at finishMaybe (/Users/tk/MEGAsync/cloud/gitbucket/material-design-lite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:500:7)
    at endWritable (/Users/tk/MEGAsync/cloud/gitbucket/material-design-lite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:512:3)
    at DestroyableTransform.Writable.end (/Users/tk/MEGAsync/cloud/gitbucket/material-design-lite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:477:5)
    at DestroyableTransform.onend (/Users/tk/MEGAsync/cloud/gitbucket/material-design-lite/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
```

**Comment by surma** [comment]
@tkisme Interesting. Could provide some more info?

* npm and node version
* Did you get the code through:
  * Downloaded zip file
  * Bower
  * Npm
  * Clone of the repo
* Version of your OS
* Why are you running `gulp demos`? Usually, people run either `gulp` to build the lib or `gulp all` to build both the website and the lib. What are you trying to do?

**Comment by kelsmj** [comment]
I am getting the same thing. 

NPM -v = 2.11.3
node -v = v0.12.7
Ubuntu = 14.04.2 LTS

I merged latest master into my fork.  I deleted my npm_modules and redid a npm install

Running gulp all

Running just gulp works.

**Comment by janzelc** [comment]
Same here; I get the error when running `gulp all`. Got the repo via cloning `git@github.com:google/material-design-lite.git`.

Running the following:
npm 2.12.1
node v0.12.6
OSX Yosemite

**Comment by tkisme** [comment]
```gulp all``` always get error and always break here
so I think ```gulp demos``` is the fastest way to test

**Comment by surma** [comment]
Finally had the time to test this out myself. I can reproduce this on master. Not sure how and when this could have gotten inas every PR runs through our CI. We will look into a fix.

**Comment by surma** [comment]
Update: I went back to 7709ad291ad889fe8f9bf9fcc63c3807f89ada83 (originally to start a `git bisect` :scissors:) and the build fails back there as well :confused: That means that one of your dependencies apparently broke backwards compatibility somehow. Not sure how that is even possible considering we have specified versions for all of our dependencies. I guess I need to go deeper.

**Comment by filipewl** [comment]
I cloned the repo.
npm: 2.11.3
node: v0.12.7
OSX Yosemite

I was having the same problem described in the issue. I was able to solve it by removing Node modules with `rm -rf node_modules` and re-rerunning `npm install`.

**Comment by tkisme** [comment]
@filipewl just like what you said,thanks
