### ISSUE TITLE
Build fails with gulp command

### ISSUE THREAD

**Issue by vasiliy-pdk** [google/material-design-lite#1545]
Build fails with `gulp` or `gulp all && gulp serve` commands.

Ubuntu 14.04, node v0.12.7 on master (  633a0399 )

```
/material-design-lite/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:3513
});
 ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vazia/dev/material-design-lite/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by surma** [comment]
Hey @vasiliy-pdk,

I can’t seem to reproduce the issue. Can you do the following for me:
```
$ git reset --hard origin/master
$ git clean -fxd
$ npm cache clean
$ npm i
$ gulp all
$ gulp serve
```

**Comment by vasiliy-pdk** [comment]
Thanks. I've retried multiple times. Got several `npm ERR! shasum check failed for ...` messages.
But seems now all dependencies had been resolved correctly and gulp finished build with success.

**Comment by addyosmani** [comment]
Closing as this appears to be fixed now.
