### ISSUE TITLE
Uniffe doesn’t behave 😭

### ISSUE THREAD

**Issue by surma** [google/material-design-lite#1561]
Add the following two line after the top comment of [`mdlComponentHandler.js`](https://github.com/google/material-design-lite/blob/9422d9fa440207dde2c9d6168f1669f86c376b99/src/mdlComponentHandler.js).

```JS
var a = 'variable';
window.a = a;
```

```
$ gulp scripts                                                                                                                                                         1 ↵
[17:52:33] Using gulpfile ~/src/github.com/google/Material-Design-Lite/gulpfile.js
[17:52:33] Starting 'jscs'...
[17:52:35] Starting 'jshint'...
[17:52:36] Finished 'jshint' after 1.22 s
[17:52:36] Finished 'jscs' after 2.62 s
[17:52:36] Starting 'scripts'...
/Users/surma/src/github.com/google/Material-Design-Lite/utils/uniffe.js:37
  if (ast.body[0].expression.callee === undefined) {
                            ^
TypeError: Cannot read property 'callee' of undefined
    at uniffe (/Users/surma/src/github.com/google/Material-Design-Lite/utils/uniffe.js:37:29)
    at DestroyableTransform._transform (/Users/surma/src/github.com/google/Material-Design-Lite/utils/uniffe.js:55:34)
    at DestroyableTransform.Transform._read (/Users/surma/src/github.com/google/Material-Design-Lite/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/surma/src/github.com/google/Material-Design-Lite/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/surma/src/github.com/google/Material-Design-Lite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/surma/src/github.com/google/Material-Design-Lite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/surma/src/github.com/google/Material-Design-Lite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at write (/Users/surma/src/github.com/google/Material-Design-Lite/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/surma/src/github.com/google/Material-Design-Lite/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/surma/src/github.com/google/Material-Design-Lite/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

(For some reason, can’t assign, so just pinging @samccone manually for this)

**Comment by surma** [comment]
Also, fun fact: Just adding `window.a = 'variable'` runs fine.

**Comment by samccone** [comment]
@surma is this still an issue?

**Comment by surma** [comment]
Nah. You fixed it a while ago :stuck_out_tongue_winking_eye:

**Comment by samccone** [comment]
:bow: cool beans!
