### ISSUE TITLE
Build error in 'mocha' task

### ISSUE THREAD

**Issue by cubicwork** [google/material-design-lite#1672]
Ubuntu 15.04 / Node V4.1.1 / npm V2.14.4
Just build MDL without any modification in source code

Same As #1342 
```
# npm install && npm install -g gulp
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
gulp@3.9.0 /usr/local/lib/node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.1 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, mkdirp@0.5.1, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.3, through2@2.0.0, multipipe@0.1.2, lodash.template@3.6.2, dateformat@1.0.11)


# gulp all && gulp serve
[14:51:29] Using gulpfile /var/www/material-design-lite-master/gulpfile.js
[14:51:29] Starting 'clean'...
[14:51:29] Finished 'clean' after 20 ms
[14:51:29] Starting 'all'...
[14:51:29] Starting 'clean'...
[14:51:29] Starting 'styletemplates'...
[14:51:29] Finished 'clean' after 420 ms
[14:51:29] Starting 'default'...
[14:51:29] Starting 'styles'...
[14:51:29] Starting 'styles-grid'...
[14:51:34] styles-grid all files 20.18 kB
[14:51:34] Finished 'styles-grid' after 4.66 s
[14:51:38] styles all files 539.56 kB
[14:51:38] Finished 'styletemplates' after 9.65 s
[14:51:38] styles all files 876.22 kB
[14:51:38] Finished 'styles' after 9.23 s
[14:51:38] Starting 'jscs'...
[14:51:39] Starting 'jshint'...
[14:51:43] Finished 'jshint' after 3.12 s
[14:51:43] Finished 'jscs' after 4.45 s
[14:51:43] Starting 'scripts'...
[14:51:45] scripts all files 417.86 kB
[14:51:45] Finished 'scripts' after 2.43 s
[14:51:45] Starting 'styles'...
[14:51:49] styles all files 1.01 MB
[14:51:49] Finished 'styles' after 3.76 s
[14:51:49] Starting 'mocha'...
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:339:9)
    at Object.<anonymous> (/var/www/material-design-lite-master/node_modules/gulp-mocha-phantomjs/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
[14:51:49] 'mocha' errored after 235 ms
[14:51:49] Error in plugin 'gulp-mocha-phantomjs'
test failed
[14:51:49] 'all' errored after 21 s
[14:51:49] Error in plugin 'run-sequence'
Message:
    An error occured in task 'mocha'.
[14:51:49] 'default' errored after 20 s
[14:51:49] Error in plugin 'run-sequence'
Message:
    An error occured in task 'all'.
[14:51:49] 'default' errored after 20 s
[14:51:49] Error in plugin 'run-sequence'
Message:
    An error occured in task 'mocha'.


# gulp
[14:32:27] Using gulpfile /var/www/material-design-lite-master/gulpfile.js
[14:32:27] Starting 'clean'...
[14:32:27] Finished 'clean' after 19 ms
[14:32:27] Starting 'default'...
[14:32:27] Starting 'styles'...
[14:32:27] Starting 'styles-grid'...
[14:32:31] styles-grid all files 20.18 kB
[14:32:31] Finished 'styles-grid' after 3.5 s
[14:32:33] styles all files 876.22 kB
[14:32:33] Finished 'styles' after 6.23 s
[14:32:33] Starting 'jscs'...
[14:32:34] Starting 'jshint'...
[14:32:38] Finished 'jshint' after 3.12 s
[14:32:38] Finished 'jscs' after 4.39 s
[14:32:38] Starting 'scripts'...
[14:32:40] scripts all files 417.86 kB
[14:32:40] Finished 'scripts' after 2.24 s
[14:32:40] Starting 'styles'...
[14:32:44] styles all files 1.01 MB
[14:32:44] Finished 'styles' after 3.91 s
[14:32:44] Starting 'mocha'...
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:339:9)
    at Object.<anonymous> (/var/www/material-design-lite-master/node_modules/gulp-mocha-phantomjs/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
[14:32:44] 'mocha' errored after 243 ms
[14:32:44] Error in plugin 'gulp-mocha-phantomjs'
test failed
[14:32:44] 'default' errored after 17 s
[14:32:44] Error in plugin 'run-sequence'
Message:
    An error occured in task 'mocha'.
```

**Comment by surma** [comment]
I can’t manage to reproduce this issue :(

IIRC, @sgomes and/or @addyosmani may have some input on this.

**Comment by cubicwork** [comment]
@surma  i will try it again with Node V 0.12. and comment this issue if problem solved.

**Comment by Garbee** [comment]
If it is the same as the other issue, please keep the conversation on existing issues. Creating new issues for the same problems creates clutter and makes searching more difficult.

**Comment by cubicwork** [comment]
@surma The error showed above is because the poor net connection during runing " npm install && npm install -g gulp ", 
When npm terminated by user or poor net connection while it is still runing or download files, this download or install procedure will stop. And the file which was canceled when downloading will not be resumed by npm when run npm again. So the code is incomplete. and show is the error above. 

the solution is 
1. uninstall nodejs and npm
2. clear all download-temp, npm, npm-cache and node_module directory in system and MDL project 
in windows is User/AppData/Local/temp User/AppData/Roaming/npm User/AppData/Roaming/npm-cache nodeJS/node-modules and Project-dir/node-modules
3. install nodejs and npm

**Comment by surma** [comment]
@cubicwork Thanks for the info. Glad you got it to work :)
