### ISSUE TITLE
Cant run gulp and not many clues on why

### ISSUE THREAD

**Issue by landed1** [google/material-design-lite#4395]
So its something in the scripts task...

[11:18:14] Starting 'scripts'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Command failed: java -jar -XX:-TieredCompilation node_modules/google-closure-compiler/compiler.jar --flagfile="/var/folders/ld/2mpqzfp93vv5t7ffpn4qz48c0000gn/T/53918bae-4be6-4320-9cf5-b0af802e549d" --compilation_level=ADVANCED_OPTIMIZATIONS --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --warning_level=VERBOSE --generate_exports=true --export_local_property_definitions=true --js_output_file="material.min.js"
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)

**Comment by Garbee** [comment]
Which branch are you trying to build from?

**Comment by landed1** [comment]
master

**Comment by Garbee** [comment]
Master is very unstable, try `mdl-1.1` to build the currently supported branch until we get `master` fleshed out some more. As of right now, we aren't directly supporting builds since we are just starting the major 2.x rework in it.

**Comment by landed1** [comment]
Ok thanks
