### ISSUE TITLE
need more instruction on readme

### ISSUE THREAD

**Issue by bochen2014** [google/material-design-lite#4836]
very disappointed..

after downloaded to my local machine, both windows and linux, can't even pass unit test
```
npm test
compains can't find babel-register
(but all compiled css and js file are in dist folder, so i"m still ready to go)
```
then I manually installed babel-register, and it comes another error.

I was trying to host the docs locally, don't know how. I'm not familiar with template engines, and can't find any instructions within the site.

**Comment by traviskaufman** [comment]
Have you tried running `npm install` before running `npm test`?

**Comment by mh-cbon** [comment]
hi,

some difficulties here too.

```sh
 1007  cd material-design-lite/
 1008  npm i
 1009  git branch
 1010  gulp
 1011  ./node_modules/.bin/gulp 
 1012  npm install --save-dev babel-core
 1013  ./node_modules/.bin/gulp 
 1014  npm install babel-core babel-preset-es2015 --save-dev
 1015  ./node_modules/.bin/gulp 
 1016  npm i node-sass --save-dev
 1017  ./node_modules/.bin/gulp 
 1018  history 
```

first output,

```sh
[05:52:00] Failed to load external module babel-register
[05:52:00] Requiring external module babel-core/register
[05:52:06] Using gulpfile ~/projects/material-design-lite/gulpfile.babel.js
[05:52:06] Starting 'clean'...
[05:52:06] Finished 'clean' after 14 ms
[05:52:06] Starting 'default'...
[05:52:06] Starting 'styles'...
[05:52:07] 'styles' errored after 726 ms
[05:52:07] Error: ENOENT: no such file or directory, scandir '/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.getInstalledBinaries (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/extensions.js:120:13)
    at foundBinariesList (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/index.js:15:28)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mh-cbon/projects/material-design-lite/node_modules/babel-core/lib/api/register/node.js:214:7)
[05:52:07] 'default' errored after 736 ms
[05:52:07] Error in plugin 'run-sequence(styles)'
Message:
    ENOENT: no such file or directory, scandir '/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/vendor'
Details:
    errno: -2
    code: ENOENT
    syscall: scandir
    path: /home/mh-cbon/projects/material-design-lite/node_modules/node-sass/vendor
Stack:
Error: ENOENT: no such file or directory, scandir '/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.getInstalledBinaries (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/extensions.js:120:13)
    at foundBinariesList (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/home/mh-cbon/projects/material-design-lite/node_modules/node-sass/lib/index.js:15:28)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mh-cbon/projects/material-design-lite/node_modules/babel-core/lib/api/register/node.js:214:7)
```

last output
```sh
[06:02:14] Failed to load external module babel-register
[06:02:14] Requiring external module babel-core/register
[06:02:14] Using gulpfile ~/projects/material-design-lite/gulpfile.babel.js
[06:02:14] Starting 'clean'...
[06:02:14] Finished 'clean' after 8.41 ms
[06:02:14] Starting 'default'...
[06:02:14] Starting 'styles'...
[06:02:16] Starting 'styles-grid'...
[06:02:19] styles-grid all files 18.82 kB
[06:02:19] Finished 'styles-grid' after 2.75 s
[06:02:21] styles all files 574.71 kB
[06:02:21] Finished 'styles' after 6.45 s
[06:02:21] Starting 'lint'...
[06:02:27] Finished 'lint' after 6.36 s
[06:02:27] Starting 'scripts'...
[06:02:31] scripts all files 270.49 kB
[06:02:31] Finished 'scripts' after 3.87 s
[06:02:31] Starting 'styles'...
[06:02:34] styles all files 574.71 kB
[06:02:34] Finished 'styles' after 3.24 s
[06:02:34] Starting 'mocha'...
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:339:9)
    at Object.<anonymous> (/home/mh-cbon/projects/material-design-lite/node_modules/phantomjs-prebuilt/bin/phantomjs:22:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
[06:02:34] 'mocha' errored after 280 ms
[06:02:34] Error in plugin 'gulp-mocha-phantomjs'
Message:
    test failed. phantomjs exit code: 1
[06:02:34] 'default' errored after 20 s
[06:02:34] Error in plugin 'run-sequence(mocha)'
Message:
    test failed. phantomjs exit code: 1
Stack:
    at finish (/home/mh-cbon/projects/material-design-lite/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/home/mh-cbon/projects/material-design-lite/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/mh-cbon/projects/material-design-lite/node_modules/orchestrator/index.js:264:8)
    at /home/mh-cbon/projects/material-design-lite/node_modules/orchestrator/index.js:275:23
    at finish (/home/mh-cbon/projects/material-design-lite/node_modules/orchestrator/lib/runTask.js:21:8)
    at DestroyableTransform.<anonymous> (/home/mh-cbon/projects/material-design-lite/node_modules/orchestrator/lib/runTask.js:52:4)
    at DestroyableTransform.f (/home/mh-cbon/projects/material-design-lite/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at emitOne (events.js:82:20)
````

That would be great to just npm i and then run the appropriate binaries from node_modules.
