### ISSUE TITLE
gulp failed to load external module babel

### ISSUE THREAD

**Issue by RoliesDonald** [google/material-design-lite#4988]
hi everyone i'm always get this 
`RoliesDonalds-MacBook-Pro:berita roliesdonald$ gulp
[15:32:41] Failed to load external module babel-core/register
[15:32:41] Failed to load external module babel/register
/Users/roliesdonald/Documents/job/newsweb/berita/gulpfile.babel.js:25
import fs from 'fs';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/Users/roliesdonald/.nvm/versions/io.js/v3.3.1/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/roliesdonald/.nvm/versions/io.js/v3.3.1/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/Users/roliesdonald/.nvm/versions/io.js/v3.3.1/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)`

my gulp version is 
`[RoliesDonalds-MacBook-Pro:berita roliesdonald$ gulp -v
[15:40:05] Failed to load external module babel-core/register
[15:40:05] Failed to load external module babel/register
[15:40:05] CLI version 3.9.0
[15:40:05] Local version 3.9.0`

anybody can help me please....

**Comment by sgomes** [comment]
@donrolies I assume you're building from the current state of `mdl-1.x`? There's several possible causes for your issue, so I'd recommend:

- `git pull`, to make sure you have the latest changes, including all the recent fixes.
- Double-checking you have the latest `package.json`, which includes the correct Babel configuration for the latest Babel releases.
- Running `npm i` to make sure you have the latest version of every package installed.

Looking at your output, it also looks like you're running io.js. That's a pretty old runtime, so I'd recommend upgrading to a stable (v7.x) or LTS (v6.9.x) version of node.js.

I've run a clean build from scratch to confirm everything is right in `mdl-1.x`, and it looks that way, so I'm closing this issue.

**Comment by RoliesDonald** [comment]
hi @sgomes this is my repo
https://github.com/RoliesDonald/mdl-sass

stil had problem 
`
RoliesDonalds-MacBook-Pro:mdl-sass roliesdonald$ gulp
[13:19:39] Requiring external module babel-register
[13:19:40] Using gulpfile ~/Documents/localgithub/mdl-sass/gulpfile.babel.js
[13:19:40] Starting 'clean'...
[13:19:40] Finished 'clean' after 14 ms
[13:19:40] Starting 'default'...
[13:19:40] Starting 'styles'...
[13:19:40] Starting 'styles-grid'...
[13:19:41] styles-grid all files 18.82 kB
[13:19:41] Finished 'styles-grid' after 995 ms
[13:19:43] styles all files 812.97 kB
[13:19:43] Finished 'styles' after 3.07 s
[13:19:43] Starting 'lint'...
[13:19:44] 'lint' errored after 740 ms
[13:19:44] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at copyConfiguration (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:920:12)
    at NodeConfiguration.Configuration._processConfig (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:459:5)
    at NodeConfiguration.Configuration.load (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:211:10)
    at Checker.configure (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/string-checker.js:62:29)
    at Checker.configure (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/checker.js:27:39)
    at Object.module.exports (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/gulp-jscs/index.js:35:10)
    at Gulp.<anonymous> (/Users/roliesdonald/Documents/localgithub/mdl-sass/gulpfile.babel.js:107:13)
    at module.exports (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/orchestrator/index.js:273:3)
[13:19:44] 'default' errored after 3.83 s
[13:19:44] TypeError in plugin 'run-sequence(lint)'
Message:
    Cannot convert undefined or null to object
Stack:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at copyConfiguration (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:920:12)
    at NodeConfiguration.Configuration._processConfig (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:459:5)
    at NodeConfiguration.Configuration.load (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:211:10)
    at Checker.configure (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/string-checker.js:62:29)
    at Checker.configure (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/checker.js:27:39)
    at Object.module.exports (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/gulp-jscs/index.js:35:10)
    at Gulp.<anonymous> (/Users/roliesdonald/Documents/localgithub/mdl-sass/gulpfile.babel.js:107:13)
    at module.exports (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/orchestrator/index.js:273:3)
`
