### ISSUE TITLE
my gulp issue

### ISSUE THREAD

**Issue by RoliesDonald** [google/material-design-lite#4989]
hi i had problem with gulp 
`RoliesDonalds-MacBook-Pro:mdl-sass roliesdonald$ gulp
[13:04:04] Requiring external module babel-register
[13:04:05] Using gulpfile ~/Documents/localgithub/mdl-sass/gulpfile.babel.js
[13:04:05] Starting 'clean'...
[13:04:05] Finished 'clean' after 20 ms
[13:04:05] Starting 'default'...
[13:04:05] Starting 'styles'...
[13:04:05] Starting 'styles-grid'...
[13:04:06] styles-grid all files 18.82 kB
[13:04:06] Finished 'styles-grid' after 933 ms
[13:04:08] styles all files 812.97 kB
[13:04:08] Finished 'styles' after 2.95 s
[13:04:08] Starting 'lint'...
[13:04:09] 'lint' errored after 664 ms
[13:04:09] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at copyConfiguration (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:920:12)
    at NodeConfiguration.Configuration._processConfig (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:459:5)
    at NodeConfiguration.Configuration.load (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:211:10)
    at Checker.configure (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/string-checker.js:62:29)
    at Checker.configure (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/checker.js:27:39)
    at Object.module.exports (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/gulp-jscs/index.js:35:10)
    at Gulp.<anonymous> (/Users/roliesdonald/Documents/localgithub/mdl-sass/gulpfile.babel.js:107:13)
    at module.exports (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/orchestrator/index.js:273:3)
[13:04:09] 'default' errored after 3.63 s
[13:04:09] TypeError in plugin 'run-sequence(lint)'
Message:
    Cannot convert undefined or null to object
Stack:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at copyConfiguration (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:920:12)
    at NodeConfiguration.Configuration._processConfig (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:459:5)
    at NodeConfiguration.Configuration.load (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/config/configuration.js:211:10)
    at Checker.configure (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/string-checker.js:62:29)
    at Checker.configure (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/jscs/lib/checker.js:27:39)
    at Object.module.exports (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/gulp-jscs/index.js:35:10)
    at Gulp.<anonymous> (/Users/roliesdonald/Documents/localgithub/mdl-sass/gulpfile.babel.js:107:13)
    at module.exports (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/roliesdonald/Documents/localgithub/mdl-sass/node_modules/orchestrator/index.js:273:3)`

any body help me please

and this my MDL clone repo :
https://github.com/RoliesDonald/mdl-sass

**Comment by sgomes** [comment]
It looks like you're having some issues with `gulp-jscs`. [Our build is clean on our CI](https://ci.cloudware.io/google/material-design-lite/898), so this looks like an issue with your particular configuration, and not something we're really able to help you with.

Perhaps [StackOverflow](http://stackoverflow.com/) would be a good place to ask for help?

In the meantime, you could also try disabling the `lint` task, as the only thing it does is check that the Javascript follows our style guidelines.
