### ISSUE TITLE
need more instructions

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#4994]
I'm using gulp on Macbook. very disappointed. help me.@Garbee @sgomes 

```
Zhaoweis-MacBook-Pro:mdl zzw$ gulp
[22:16:45] Requiring external module babel-register
[22:16:45] Using gulpfile ~/Documents/Site/MDL/mdl/gulpfile.babel.js
[22:16:45] Starting 'clean'...
[22:16:45] Finished 'clean' after 11 ms
[22:16:45] Starting 'default'...
[22:16:45] Starting 'styles'...
[22:16:45] Starting 'styles-grid'...
[22:16:46] styles-grid all files 18.82 kB
[22:16:46] Finished 'styles-grid' after 607 ms
[22:16:47] styles all files 812.99 kB
[22:16:47] Finished 'styles' after 1.86 s
[22:16:47] Starting 'lint'...
[22:16:49] Finished 'lint' after 1.43 s
[22:16:49] Starting 'scripts'...
[22:16:49] scripts all files 270.9 kB
[22:16:49] Finished 'scripts' after 899 ms
[22:16:49] Starting 'styles'...
[22:16:51] styles all files 812.99 kB
[22:16:51] Finished 'styles' after 1.26 s
[22:16:51] Starting 'mocha'...
Error loading resource file:///Users/zzw/Documents/Site/MDL/mdl/node_modules/mocha/mocha.css (203). Details: Error opening /Users/zzw/Documents/Site/MDL/mdl/node_modules/mocha/mocha.css: No such file or directory
Error loading resource file:///Users/zzw/Documents/Site/MDL/mdl/node_modules/jquery/dist/jquery.js (203). Details: Error opening /Users/zzw/Documents/Site/MDL/mdl/node_modules/jquery/dist/jquery.js: No such file or directory
Error loading resource file:///Users/zzw/Documents/Site/MDL/mdl/node_modules/mocha/mocha.js (203). Details: Error opening /Users/zzw/Documents/Site/MDL/mdl/node_modules/mocha/mocha.js: No such file or directory
Error loading resource file:///Users/zzw/Documents/Site/MDL/mdl/node_modules/chai/chai.js (203). Details: Error opening /Users/zzw/Documents/Site/MDL/mdl/node_modules/chai/chai.js: No such file or directory
Error loading resource file:///Users/zzw/Documents/Site/MDL/mdl/node_modules/chai-jquery/chai-jquery.js (203). Details: Error opening /Users/zzw/Documents/Site/MDL/mdl/node_modules/chai-jquery/chai-jquery.js: No such file or directory
TypeError: undefined is not a constructor (evaluating 'mocha.setup('bdd')')

   in global code at file:///Users/zzw/Documents/Site/MDL/mdl/test/index.html:47
[22:16:55] 'mocha' errored after 3.86 s
[22:16:55] Error in plugin 'gulp-mocha-phantomjs'
Message:
    test failed. phantomjs exit code: 1
[22:16:55] 'default' errored after 9.3 s
[22:16:55] Error in plugin 'run-sequence(mocha)'
Message:
    test failed. phantomjs exit code: 1
Stack:
    at finish (/Users/zzw/Documents/Site/MDL/mdl/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/zzw/Documents/Site/MDL/mdl/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/zzw/Documents/Site/MDL/mdl/node_modules/orchestrator/index.js:264:8)
    at /Users/zzw/Documents/Site/MDL/mdl/node_modules/orchestrator/index.js:275:23
    at finish (/Users/zzw/Documents/Site/MDL/mdl/node_modules/orchestrator/lib/runTask.js:21:8)
    at DestroyableTransform.<anonymous> (/Users/zzw/Documents/Site/MDL/mdl/node_modules/orchestrator/lib/runTask.js:52:4)
    at DestroyableTransform.f (/Users/zzw/Documents/Site/MDL/mdl/node_modules/once/once.js:17:25)
    at emitOne (events.js:101:20)
```

**Comment by sgomes** [comment]
Looks like you're missing some dependencies. Instructions are at https://getmdl.io/started/index.html (make sure to click the "Build" tab).
