### ISSUE TITLE
Looking for help with Gulp testing

### ISSUE THREAD

**Issue by eKoopmans** [google/material-design-lite#5059]
Hi there! I've developed a new MDL component (`search`, based on [this reference](https://material.io/guidelines/patterns/search.html)) and I plan to submit a PR in the next day or two, as soon as I get it passing the tests. Right now I'm having some trouble with testing - I'm new to Gulp so it could be a variety of things.

Here are the steps I've followed:

1. Cloned `mdl-1.x`.
2. Made a branch, `ekoopmans/feature/search`.
3. Added `src/search/` with JS, SCSS, readme, snippets, and unit test (in `test/unit/`).
4. Updated `_variables.scss`, `test/index.html`, and `test/visual/index.html`.
5. Ran `npm install` at the root level - this generated several warnings, which I've copied below.
6. Ran `npm test` (also `gulp test`), which encounters an error in plugin `gulp-jscs`.
7. Scratched my head, because the error message isn't very descriptive:

```
[01:36:33] Requiring external module babel-register
[01:36:34] Using gulpfile D:\mdl-git\gulpfile.babel.js
[01:36:34] Starting 'clean'...
[01:36:34] Finished 'clean' after 14 ms
[01:36:34] Starting 'default'...
[01:36:34] Starting 'styles'...
[01:36:34] Starting 'styles-grid'...
[01:36:37] styles-grid all files 18.82 kB
[01:36:37] Finished 'styles-grid' after 2.45 s
[01:36:37] styles all files 840.57 kB
[01:36:37] Finished 'styles' after 2.74 s
[01:36:37] Starting 'lint'...
    ... (all files returned "1 code style error found", including my `search.js`) ...
[01:36:39] 'lint' errored after 2.18 s
[01:36:39] Error in plugin 'gulp-jscs'
Message:
    JSCS failed for: D:\mdl-git\src\mdlComponentHandler.js, D:\mdl-git\src\animation\demo.js, D:\mdl-git\src\button\button.js, D:\mdl-git\src\checkbox\checkbox.js, D:\mdl-git\src\data-table\data-table.js, D:\mdl-git\src\icon-toggle\icon-toggle.js, D:\mdl-git\src\layout\layout.js, D:\mdl-git\src\menu\menu.js, D:\mdl-git\src\progress\progress.js, D:\mdl-git\src\radio\radio.js, D:\mdl-git\src\ripple\ripple.js, D:\mdl-git\src\search\search.js, D:\mdl-git\src\slider\slider.js, D:\mdl-git\src\snackbar\snackbar.js, D:\mdl-git\src\spinner\spinner.js, D:\mdl-git\src\switch\switch.js, D:\mdl-git\src\tabs\tabs.js, D:\mdl-git\src\textfield\textfield.js, D:\mdl-git\src\third_party\rAF.js, D:\mdl-git\src\tooltip\tooltip.js, D:\mdl-git\gulpfile.babel.js
[01:36:39] 'default' errored after 4.93 s
[01:36:39] Error in plugin 'run-sequence(lint)'
Message:
    JSCS failed for: D:\mdl-git\src\mdlComponentHandler.js, D:\mdl-git\src\animation\demo.js, D:\mdl-git\src\button\button.js, D:\mdl-git\src\checkbox\checkbox.js, D:\mdl-git\src\data-table\data-table.js, D:\mdl-git\src\icon-toggle\icon-toggle.js, D:\mdl-git\src\layout\layout.js, D:\mdl-git\src\menu\menu.js, D:\mdl-git\src\progress\progress.js, D:\mdl-git\src\radio\radio.js, D:\mdl-git\src\ripple\ripple.js, D:\mdl-git\src\search\search.js, D:\mdl-git\src\slider\slider.js, D:\mdl-git\src\snackbar\snackbar.js, D:\mdl-git\src\spinner\spinner.js, D:\mdl-git\src\switch\switch.js, D:\mdl-git\src\tabs\tabs.js, D:\mdl-git\src\textfield\textfield.js, D:\mdl-git\src\third_party\rAF.js, D:\mdl-git\src\tooltip\tooltip.js, D:\mdl-git\gulpfile.babel.js
Stack:
    at finish (D:\mdl-git\node_modules\run-sequence\index.js:56:13)
    at Gulp.onError (D:\mdl-git\node_modules\run-sequence\index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (D:\mdl-git\node_modules\orchestrator\index.js:264:8)
    at D:\mdl-git\node_modules\orchestrator\index.js:275:23
    at finish (D:\mdl-git\node_modules\orchestrator\lib\runTask.js:21:8)
    at DestroyableTransform.<anonymous> (D:\mdl-git\node_modules\orchestrator\lib\runTask.js:52:4)
    at DestroyableTransform.f (D:\mdl-git\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at emitOne (events.js:101:20)
'Please commit all changes generated by building'; exit 1
```

So I see that it's encountering an error with JSCS as part of the `lint` task, line 106 of `gulpfile.babel.js`, but it's not clear to me what's causing JSCS to fail. What I can say is that I encounter the same problem running `npm test` on the unedited `mdl-1.x` branch, so I assume it's not my code. Here are the warnings I received on `npm install`:

```
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global node-gyp@3.5.0 should be installed with -g
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

I'm running Node v6.10.0 on Windows 10. Thanks, I appreciate any help and I'm looking forward to getting this PR rolling!

**Comment by Garbee** [comment]
Did you check the files out with unix-style line endings? That is enforced by JSCS and you're on Windows which by default does its own thing with line endings. You need to specifically checkout the repo and have it convert to unix-style and write new stuff with your editor configured to do unix-style endings over Windows-style.

The warnings are just warnings and not relevant for the most part. The few that are don't cause any real problems with our usage since things are all ran locally and the compiled output is pushed elsewhere.

**Comment by eKoopmans** [comment]
Thanks @Garbee, that was the problem. It's now passing all tests, PR is incoming!
